server:
  port: 8000
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #与服务注册发现组件结合，直接使用应用名称调用服务，http://gateway/base-service(服务名)/baseCode/queryForCodeSelect
          lowerCaseServiceId: true

ribbon:
  ConnectTimeout: 60000
  ReadTimeout: 60000

hystrix:
  command:
    default: #default全局有效，service id指定应用有效
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000 #断路器超时时间，默认1000ms
      circuitBreaker:
        requestVolumeThreshold: 20 #默认20，时间窗口10s内请求失败数量达到20个，断路器开
        sleepWindowInMilliseconds: 5000 #短路多久以后开始尝试是否恢复，默认5s
        errorThresholdPercentage: 50 #出错百分比阈值，当达到此阈值后，开始短路。默认50%
  threadpool:
    default:
      coreSize: 120 #并发执行的最大线程数，默认10
      maxQueueSize: -1 #默认-1，最大排队长度
      queueSizeRejectionThreshold: 5 #排队线程数量阈值，默认为5，达到时拒绝。maxQueueSize=-1的话，则该选项不起作用

#actuator 默认关闭所有endpoint，只打开health。
management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
      show-details: always
  health:
    diskspace:
      enabled: true            #为false时只显示{"status":"UP"}，不显示明细
      threshold: 10737418240 #空闲磁盘阀值<10737418240 bytes / 1024 /1024 /1024 = 10G
    db:
      enabled: true
    redis:
      enabled: true
    elasticsearch:
      enabled: true

customer:
  request:
    timestampGap: 1800 #服务器允许的客户端时间误差，秒
    rejectIPList: 192.168.5.5,192.168.1.2 #服务器拒绝访问ip名单
    transparentUrls: #网关透明传输的url，不做任何处理
      - /auth-service/dict/queryForCodeSelect
      - /auth-service/help/querytitleByCategory
      - /auth-service/help/searchKeyWord
      - /auth-service/help/queryById
      - /auth-service/file/upload
      - /auth-service/file/download
    skipValidateSign:
      - /auth-service/user/login
      - /auth-service/user/captcha/get
      - /auth-service/user/captcha/check
    skipValidateTimestamp:
      - /auth-service/user/login
    skipValidateToken:
      - /auth-service/user/login
      - /auth-service/user/logout
      - /auth-service/user/captcha/get
      - /auth-service/user/captcha/check
    skipValidateAuth:
      - /auth-service/user/login
      - /auth-service/user/logout
      - /auth-service/user/captcha/get
      - /auth-service/user/captcha/check
    skipValidateLog:
      - /auth-service/user/logout
      - /auth-service/user/captcha/get
      - /auth-service/user/captcha/check
